name: CI
on:
  push:
    tags:
    - '*'
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract tag name
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fe:${{ steps.tag.outputs.tag }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fe:${{ steps.tag.outputs.tag }}

      - name: Clone config repo
        uses: actions/checkout@v3
        with:
          repository: hungitb/test-fe-config
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Update and push to config repo
        run: |
          sed -i 's/image: hungitb\/fe.*/image: hungitb\/fe:${{ steps.tag.outputs.tag }}/' values.yaml
          git config user.name "hungitb" && git config user.email "hungnv.itb@gmail.com"
          git add . && git commit -m update && git push origin main
